# Use postgres/example user/password credentials
version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Mudar@2023
      - POSTGRES_DB=paymentdb
    ports:
      - "5432:5432"